import type { Asset, InventoryPart, MaintenanceSchedule, MonitoringDoc, WorkOrder } from '../../types'

/**
 * Pure demo dataset for the NextGen CMMS. Used by the in-app injector
 * (Settings page) and the CLI seed. `parentKey`/`assetKey` references are
 * resolved to Firestore ids by the seeder.
 */

const now = Date.now()
const HOUR = 3_600_000
const DAY = 86_400_000
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString()

/* ------------------------------------------------------------------ */

interface SeedAssetInput extends Omit<Asset, 'id' | 'parentId'> {
  key: string
  parentKey: string | null
}

export const DEMO_ASSETS: SeedAssetInput[] = [
  {
    key: 'facility',
    parentKey: null,
    name: 'Tembisa Industrial Plant',
    location: 'Head Office, Midrand',
    category: 'Facility',
    status: 'operational',
    qrCode: 'NGCMNS-FACILITY-001',
    healthScore: 98,
    thresholds: { tempMax: 80, vibrationMax: 6, runHoursMax: 200 },
    metrics: { runHours: 12_400, temp: 26, vibration: 0.4, updatedAt: iso(-2 * HOUR) },
    createdAt: iso(-200 * DAY),
    updatedAt: iso(-2 * HOUR),
  },
  {
    key: 'linea',
    parentKey: 'facility',
    name: 'Production Line A',
    location: 'Bay 1',
    category: 'Production',
    status: 'operational',
    qrCode: 'NGCMNS-LINE-A-002',
    healthScore: 94,
    thresholds: { tempMax: 75, vibrationMax: 5, runHoursMax: 150 },
    metrics: { runHours: 3_100, temp: 32, vibration: 0.8, updatedAt: iso(-1 * HOUR) },
    createdAt: iso(-180 * DAY),
    updatedAt: iso(-1 * HOUR),
  },
  {
    key: 'lineb',
    parentKey: 'facility',
    name: 'Production Line B',
    location: 'Bay 2',
    category: 'Production',
    status: 'degraded',
    qrCode: 'NGCMNS-LINE-B-003',
    healthScore: 58,
    thresholds: { tempMax: 75, vibrationMax: 5, runHoursMax: 150 },
    metrics: { runHours: 4_900, temp: 48, vibration: 2.1, updatedAt: iso(-20 * 60_000) },
    createdAt: iso(-180 * DAY),
    updatedAt: iso(-20 * 60_000),
  },
  {
    key: 'utils',
    parentKey: 'facility',
    name: 'Utilities',
    location: 'Plant Services',
    category: 'Facility',
    status: 'operational',
    qrCode: 'NGCMNS-UTIL-010',
    healthScore: 90,
    thresholds: { tempMax: 70, vibrationMax: 5, runHoursMax: 160 },
    metrics: { runHours: 6_400, temp: 30, vibration: 0.5, updatedAt: iso(-3 * HOUR) },
    createdAt: iso(-170 * DAY),
    updatedAt: iso(-3 * HOUR),
  },
  {
    key: 'p101',
    parentKey: 'linea',
    name: 'Compressor P-101',
    location: 'Bay 1 · Skid A',
    category: 'Compressor',
    status: 'down',
    qrCode: 'NGCMNS-P101-004',
    healthScore: 12,
    thresholds: { tempMax: 70, vibrationMax: 4.5, runHoursMax: 100 },
    metrics: { runHours: 2_940, temp: 96, vibration: 8.4, updatedAt: iso(-8 * 60_000) },
    createdAt: iso(-150 * DAY),
    updatedAt: iso(-8 * 60_000),
  },
  {
    key: 'c201',
    parentKey: 'linea',
    name: 'Conveyor C-201',
    location: 'Bay 1 · Transfer',
    category: 'Conveyor',
    status: 'operational',
    qrCode: 'NGCMNS-C201-005',
    healthScore: 88,
    thresholds: { tempMax: 65, vibrationMax: 5, runHoursMax: 120 },
    metrics: { runHours: 1_880, temp: 44, vibration: 1.2, updatedAt: iso(-1 * HOUR) },
    createdAt: iso(-140 * DAY),
    updatedAt: iso(-1 * HOUR),
  },
  {
    key: 'm301',
    parentKey: 'linea',
    name: 'Mixer M-301',
    location: 'Bay 1 · Blend',
    category: 'Mixer',
    status: 'operational',
    qrCode: 'NGCMNS-M301-006',
    healthScore: 92,
    thresholds: { tempMax: 70, vibrationMax: 5, runHoursMax: 130 },
    metrics: { runHours: 2_240, temp: 50, vibration: 1.6, updatedAt: iso(-2 * HOUR) },
    createdAt: iso(-130 * DAY),
    updatedAt: iso(-2 * HOUR),
  },
  {
    key: 'p102',
    parentKey: 'lineb',
    name: 'Compressor P-102',
    location: 'Bay 2 · Skid B',
    category: 'Compressor',
    status: 'degraded',
    qrCode: 'NGCMNS-P102-007',
    healthScore: 45,
    thresholds: { tempMax: 70, vibrationMax: 4.5, runHoursMax: 100 },
    metrics: { runHours: 3_400, temp: 73, vibration: 4.0, updatedAt: iso(-25 * 60_000) },
    createdAt: iso(-120 * DAY),
    updatedAt: iso(-25 * 60_000),
  },
  {
    key: 'p401',
    parentKey: 'lineb',
    name: 'Pump P-401',
    location: 'Bay 2 · Dosing',
    category: 'Pump',
    status: 'degraded',
    qrCode: 'NGCMNS-P401-008',
    healthScore: 39,
    thresholds: { tempMax: 60, vibrationMax: 4, runHoursMax: 90 },
    metrics: { runHours: 4_600, temp: 61, vibration: 5.2, updatedAt: iso(-30 * 60_000) },
    createdAt: iso(-110 * DAY),
    updatedAt: iso(-30 * 60_000),
  },
  {
    key: 'u501',
    parentKey: 'utils',
    name: 'HVAC Chiller U-501',
    location: 'Plant Services',
    category: 'HVAC',
    status: 'operational',
    qrCode: 'NGCMNS-U501-009',
    healthScore: 85,
    thresholds: { tempMax: 65, vibrationMax: 4, runHoursMax: 140 },
    metrics: { runHours: 5_200, temp: 42, vibration: 0.7, updatedAt: iso(-3 * HOUR) },
    createdAt: iso(-100 * DAY),
    updatedAt: iso(-3 * HOUR),
  },
  {
    key: 'u601',
    parentKey: 'utils',
    name: 'Air Dryer U-601',
    location: 'Plant Services',
    category: 'Utility',
    status: 'operational',
    qrCode: 'NGCMNS-U601-011',
    healthScore: 96,
    thresholds: { tempMax: 60, vibrationMax: 4, runHoursMax: 150 },
    metrics: { runHours: 7_800, temp: 34, vibration: 0.6, updatedAt: iso(-4 * HOUR) },
    createdAt: iso(-90 * DAY),
    updatedAt: iso(-4 * HOUR),
  },
]

/* ------------------------------------------------------------------ */

export const DEMO_PARTS: Omit<InventoryPart, 'id'>[] = [
  {
    partNumber: 'BRG-6205-2RS',
    name: 'Deep groove ball bearing 6205 2RS',
    quantityOnHand: 4,
    minReorderPoint: 10,
    cost: 24.5,
    assignedAssets: ['Compressor P-101', 'Pump P-401'],
    reorderQty: 20,
    updatedAt: iso(-1 * DAY),
  },
  {
    partNumber: 'OIL-SYNC-32',
    name: 'Synthetic compressor oil (5L)',
    quantityOnHand: 2,
    minReorderPoint: 6,
    cost: 48,
    assignedAssets: ['Compressor P-101', 'Compressor P-102'],
    reorderQty: 12,
    updatedAt: iso(-2 * DAY),
  },
  {
    partNumber: 'FLT-PN-160',
    name: 'Panel air filter 160mm',
    quantityOnHand: 14,
    minReorderPoint: 8,
    cost: 12.75,
    assignedAssets: ['HVAC Chiller U-501'],
    reorderQty: 24,
    updatedAt: iso(-3 * DAY),
  },
  {
    partNumber: 'SEA-MECH-40',
    name: 'Mechanical seal 40mm pump',
    quantityOnHand: 3,
    minReorderPoint: 4,
    cost: 87,
    assignedAssets: ['Pump P-401'],
    reorderQty: 10,
    updatedAt: iso(-4 * DAY),
  },
  {
    partNumber: 'BLT-A-1050',
    name: 'V-belt A1050 (conveyor drive)',
    quantityOnHand: 22,
    minReorderPoint: 6,
    cost: 9.2,
    assignedAssets: ['Conveyor C-201'],
    reorderQty: 24,
    updatedAt: iso(-5 * DAY),
  },
  {
    partNumber: 'MOT-11KW-IE3',
    name: 'Electric motor 11 kW IE3',
    quantityOnHand: 1,
    minReorderPoint: 2,
    cost: 1450,
    assignedAssets: ['Mixer M-301'],
    reorderQty: 2,
    updatedAt: iso(-6 * DAY),
  },
  {
    partNumber: 'RFD-3PH-315',
    name: 'Refrigerant R410A cylinder',
    quantityOnHand: 9,
    minReorderPoint: 3,
    cost: 210,
    assignedAssets: ['HVAC Chiller U-501'],
    reorderQty: 6,
    updatedAt: iso(-7 * DAY),
  },
]

/* ------------------------------------------------------------------ */

// Work orders / schedules / monitoring reference assets by seed key.

export const DEMO_WORK_ORDERS: Omit<WorkOrder, 'id'>[] = [
  {
    assetId: 'p101',
    assetName: 'Compressor P-101',
    title: 'Compressor overheating - high discharge temp (IoT alert HOT)',
    description: 'Auto-generated by condition monitoring: temp exceeded 70°C threshold.',
    priority: 'critical',
    status: 'open',
    assignedTo: 'Unassigned',
    triggerType: 'iot_sensor',
    offlineCreated: false,
    createdAt: iso(-50 * 60_000),
    completedAt: null,
    updatedAt: iso(-50 * 60_000),
  },
  {
    assetId: 'p401',
    assetName: 'Pump P-401',
    title: 'Excessive vibration - scheduled balancing',
    description: 'Vibration trending 5.2 mm/s against a 4.0 mm/s limit.',
    priority: 'high',
    status: 'in_progress',
    assignedTo: 'T. Mokoena',
    triggerType: 'iot_sensor',
    offlineCreated: false,
    createdAt: iso(-6 * HOUR),
    completedAt: null,
    updatedAt: iso(-1 * HOUR),
  },
  {
    assetId: 'lineb',
    assetName: 'Production Line B',
    title: 'Weekly line inspection & lubrication',
    description: 'Standard PM round on all line-B rotating equipment.',
    priority: 'medium',
    status: 'in_progress',
    assignedTo: 'S. Nkosi',
    triggerType: 'calendar',
    offlineCreated: false,
    createdAt: iso(-1 * DAY),
    completedAt: null,
    updatedAt: iso(-12 * HOUR),
  },
  {
    assetId: 'p401',
    assetName: 'Pump P-401',
    title: 'Replace mechanical seal & service casing',
    description: 'Leak detected at gland packing during last inspection.',
    priority: 'high',
    status: 'open',
    assignedTo: 'Unassigned',
    triggerType: 'manual',
    offlineCreated: false,
    createdAt: iso(-2 * DAY),
    completedAt: null,
    updatedAt: iso(-2 * DAY),
  },
  {
    assetId: 'c201',
    assetName: 'Conveyor C-201',
    title: 'Belt tensioning after 1800 run hours',
    description: 'Meter-based maintenance due.',
    priority: 'low',
    status: 'completed',
    assignedTo: 'J. Fourie',
    triggerType: 'meter',
    offlineCreated: false,
    createdAt: iso(-5 * DAY),
    completedAt: iso(-4 * DAY),
    updatedAt: iso(-4 * DAY),
  },
  {
    assetId: 'u501',
    assetName: 'HVAC Chiller U-501',
    title: 'Refrigerant top-up & pressure test',
    description: '',
    priority: 'medium',
    status: 'completed',
    assignedTo: 'R. Dlamini',
    triggerType: 'calendar',
    offlineCreated: false,
    createdAt: iso(-8 * DAY),
    completedAt: iso(-6 * DAY),
    updatedAt: iso(-6 * DAY),
  },
  {
    assetId: 'm301',
    assetName: 'Mixer M-301',
    title: 'Internet-down field fix: guard reattach (offline created)',
    description: 'Created on a tablet while on the plant floor without connectivity.',
    priority: 'low',
    status: 'open',
    assignedTo: 'T. Mokoena',
    triggerType: 'manual',
    offlineCreated: true,
    createdAt: iso(-12 * HOUR),
    completedAt: null,
    updatedAt: iso(-12 * HOUR),
  },
  {
    assetId: 'p102',
    assetName: 'Compressor P-102',
    title: 'Oil change service',
    description: 'Routine 3000-hour compressor service.',
    priority: 'medium',
    status: 'completed',
    assignedTo: 'S. Nkosi',
    triggerType: 'calendar',
    offlineCreated: false,
    createdAt: iso(-12 * DAY),
    completedAt: iso(-10 * DAY),
    updatedAt: iso(-10 * DAY),
  },
]

/* ------------------------------------------------------------------ */

export const DEMO_SCHEDULES: Omit<MaintenanceSchedule, 'id'>[] = [
  {
    assetId: 'p101',
    assetName: 'Compressor P-101',
    title: 'Compressor quarterly inspection',
    frequencyDays: 90,
    meterInterval: null,
    lastExecuted: iso(-95 * DAY),
    nextDue: iso(-5 * DAY),
    updatedAt: iso(-5 * DAY),
  },
  {
    assetId: 'c201',
    assetName: 'Conveyor C-201',
    title: 'Belt & tracking check',
    frequencyDays: 30,
    meterInterval: null,
    lastExecuted: iso(-28 * DAY),
    nextDue: iso(2 * DAY),
    updatedAt: iso(-1 * DAY),
  },
  {
    assetId: 'p401',
    assetName: 'Pump P-401',
    title: 'Pump lubrication & packing',
    frequencyDays: 21,
    meterInterval: 500,
    lastExecuted: iso(-20 * DAY),
    nextDue: iso(1 * DAY),
    updatedAt: iso(-1 * DAY),
  },
  {
    assetId: 'u501',
    assetName: 'HVAC Chiller U-501',
    title: 'Chiller coil cleaning',
    frequencyDays: 60,
    meterInterval: null,
    lastExecuted: iso(-40 * DAY),
    nextDue: iso(20 * DAY),
    updatedAt: iso(-1 * DAY),
  },
  {
    assetId: 'm301',
    assetName: 'Mixer M-301',
    title: 'Mixer gearbox oil change',
    frequencyDays: 180,
    meterInterval: null,
    lastExecuted: iso(-120 * DAY),
    nextDue: iso(60 * DAY),
    updatedAt: iso(-1 * DAY),
  },
]

/* ------------------------------------------------------------------ */

export const DEMO_MONITORING: Omit<MonitoringDoc, 'id'>[] = [
  {
    assetId: 'p101',
    name: 'Compressor P-101',
    location: 'Bay 1 · Skid A',
    temp: 96,
    vibration: 8.4,
    runHours: 2940,
    thresholds: { tempMax: 70, vibrationMax: 4.5, runHoursMax: 100 },
    status: 'down',
    breached: ['HOT', 'VIBRATION', 'RUN_HOURS'],
    lastReadingAt: now - 8 * 60_000,
    readCount: 240,
    enabled: true,
  },
  {
    assetId: 'p401',
    name: 'Pump P-401',
    location: 'Bay 2 · Dosing',
    temp: 61,
    vibration: 5.2,
    runHours: 4600,
    thresholds: { tempMax: 60, vibrationMax: 4, runHoursMax: 90 },
    status: 'degraded',
    breached: ['HOT', 'VIBRATION', 'RUN_HOURS'],
    lastReadingAt: now - 30 * 60_000,
    readCount: 180,
    enabled: true,
  },
  {
    assetId: 'p102',
    name: 'Compressor P-102',
    location: 'Bay 2 · Skid B',
    temp: 73,
    vibration: 4.0,
    runHours: 3400,
    thresholds: { tempMax: 70, vibrationMax: 4.5, runHoursMax: 100 },
    status: 'degraded',
    breached: ['HOT'],
    lastReadingAt: now - 25 * 60_000,
    readCount: 160,
    enabled: true,
  },
  {
    assetId: 'c201',
    name: 'Conveyor C-201',
    location: 'Bay 1 · Transfer',
    temp: 44,
    vibration: 1.2,
    runHours: 1880,
    thresholds: { tempMax: 65, vibrationMax: 5, runHoursMax: 120 },
    status: 'operational',
    breached: ['NORMAL'],
    lastReadingAt: now - 1 * HOUR,
    readCount: 96,
    enabled: true,
  },
  {
    assetId: 'u501',
    name: 'HVAC Chiller U-501',
    location: 'Plant Services',
    temp: 42,
    vibration: 0.7,
    runHours: 5200,
    thresholds: { tempMax: 65, vibrationMax: 4, runHoursMax: 140 },
    status: 'operational',
    breached: ['NORMAL'],
    lastReadingAt: now - 3 * HOUR,
    readCount: 300,
    enabled: true,
  },
]